#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cleverence.Barcoding.Integration.Resource", IsApplication=true)]

namespace Cleverence.Barcoding.Integration
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int buttonCreate = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int buttonDataMatrix = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int buttonDispose = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int buttonEan13 = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int buttonExit = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int buttonPdf417 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int buttonSettings = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int buttonStartScan = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int buttonStopScan = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int scrollView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textDeviceId = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int textHasKeyboard = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int textResult = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int textScannerStatus = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LayoutTest = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Sherlock_Light = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
